<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
        <meta http-equiv="Content-Language" content="en-US" >
        <title>Jquery Wysiwyg</title>


        <link href="src/style.css" media="screen" rel="stylesheet" type="text/css" >

        <link href="google-ui/css/css3-buttons.css" media="screen" rel="stylesheet" type="text/css" >

        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" >
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.js"></script>

        <script type="text/javascript" src="src/wysiwyg.js"></script>
    </head>
    <body>

        <textarea name="demo" id="demo">Hello World</textarea>

        <div id="toolbar">
            <button class="button left toolbar-button" cmd="bold" status="isBold" title="Bold"><span class="icon icon20"></span></button>
            <button class="button middle toolbar-button" cmd="italic"  param="italic" status="isItalic" title="Italic"><span class="icon icon114"></span></button>
            <button class="button right toolbar-button" cmd="underline" param="underline" status="isUnderline" title="Underline"><span class="icon icon187"></span></button>

            <button class="button left toolbar-button" cmd="indent" title="indent"><span class="icon icon204"></span></button>
            <button class="button right toolbar-button" cmd="outdent" title="Outdent"><span class="icon icon205"></span></button>

            <button class="button left toolbar-button" cmd="list" param="true"  title="Ordered"><span class="icon icon201"></span></button>
            <button class="button right toolbar-button" cmd="list" title="Unordered"><span class="icon icon120"></span></button>

            <button class="button left toolbar-button" cmd="justify" param="left" status="isJustify" title="Justify left"><span class="icon icon138"></span></button>
            <button class="button middle toolbar-button" cmd="justify" param="center" status="isJustify" title="Justify center"><span class="icon icon140"></span></button>
            <button class="button right toolbar-button" cmd="justify" param="right" status="isJustify" title="Justify right"><span class="icon icon139"></span></button>

            <button class="button left toolbar-button" cmd="link" param="true" title="Insert link"><span class="icon icon119"></span></button>
            <button class="button right toolbar-button" cmd="unlink" title="Remove link"><span class="icon icon25"></span></button>

            <button class="button toolbar-button" cmd="image" title="Insert image"><span class="icon icon148"></span></button>

            <button class="button toolbar-button" cmd="removeFormat" title="Remove formatting"><span class="icon icon83"></span></button>

        </div>
        <div id="toolbar2">
            <div class="dropdown">
                <button class="button" title="Format block"><span>&lt;P&gt;</span><span class="toggle">&nbsp;</span></button>
                <div class="dropdown-slider">
                    <button class="button toolbar-button ddm"  cmd="format" param="p" title="Insert &lt;p&gt;">Paragraph</button>
                    <button class="button toolbar-button ddm"  cmd="format" param="h1" title="Insert &lt;h1&gt;">Heading 1</button>
                    <button class="button toolbar-button ddm"  cmd="format" param="h2" title="Insert &lt;h2&gt;">Heading 2</button>
                    <button class="button toolbar-button ddm"  cmd="format" param="h3" title="Insert &lt;h3&gt;">Heading 3</button>
                    <button class="button toolbar-button ddm"  cmd="format" param="h4" title="Insert &lt;h4&gt;">Heading 4</button>
                    <button class="button toolbar-button ddm"  cmd="format" param="h5" title="Insert &lt;h5&gt;">Heading 5</button>
                    <button class="button toolbar-button ddm"  cmd="format" param="h6" title="Insert &lt;h6&gt;">Heading 6</button>
                    <button class="button toolbar-button ddm"  cmd="format" param="pre" title="Insert &lt;pre&gt;">Code</button>
                    <button class="button toolbar-button ddm"  cmd="format" param="blockquote" title="Insert &lt;blockquote&gt;">Blockquote</button>
                </div>
            </div>

            <div class="dropdown">
                <button class="button" title="Format block"><span>Insert</span><span class="toggle">&nbsp;</span></button>
                <div class="dropdown-slider">
                    <button class="button toolbar-button ddm"  cmd="tag" param="br" title="Insert &lt;br&gt;">Line Break</button>
                    <button class="button toolbar-button ddm"  cmd="tag" param="hr" title="Insert &lt;hr&gt;">Horizontal rule</button>
                    <button class="button toolbar-button ddm"  cmd="quote" title="Insert &lt;quote&gt;">Quote</button>
                </div>
            </div>

            <div class="dropdown">
                <button class="button" title="Change font face"><span class="icon icon93 dropdown-icon"></span><span class="dropdown-label"></span><span class="toggle">&nbsp;</span></button>
                <div class="dropdown-slider">
                    <button class="toolbar-button ddm"  cmd="fontName" param="serif" status="isFontFace" style="font-family: serif">Serif</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="sans-serif" status="isFontFace" style="font-family: sans-serif">Sans Serif</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="monospace" status="isFontFace" style="font-family: monospace">Monospace</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Arial" status="isFontFace" style="font-family: Arial">Arial</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Helvetica" status="isFontFace" style="font-family: Helvetica">Helvetica</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Palatino" status="isFontFace" style="font-family: Palatino">Palatino</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Garamond" status="isFontFace" style="font-family: Garamond">Garamond</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Bookman" status="isFontFace" style="font-family: Bookman">Bookman</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Avant Garde" status="isFontFace" style="font-family: Avant Garde">Avant Garde</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Verdana" status="isFontFace" style="font-family: Verdana">Verdana</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Georgia" status="isFontFace" style="font-family: Georgia">Georgia</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Comic Sans MS" status="isFontFace" style="font-family: Comic Sans MS">Comic Sans MS</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Trebuchet MS" status="isFontFace" style="font-family: Trebuchet MS">Trebuchet MS</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Arial Black" status="isFontFace" style="font-family: Arial Black">Arial Black</button>
                    <button class="toolbar-button ddm"  cmd="fontName" param="Impact" status="isFontFace" style="font-family: Impact">Impact</button>
                </div>
            </div>

            <div class="dropdown" id="fontSize">
                <button class="button" title="Change font size"><span class="icon icon94 dropdown-icon"></span><span class="dropdown-label"></span><span class="toggle">&nbsp;</span></button>
                <div class="dropdown-slider" style="width:200px">
                    <button class="toolbar-button ddm"  cmd="fontSize" param="1" status="isFontSize" style="font-size: x-small">The smallest</button>
                    <button class="toolbar-button ddm"  cmd="fontSize" param="2" status="isFontSize" style="font-size: small">Small</button>
                    <button class="toolbar-button ddm"  cmd="fontSize" param="3" status="isFontSize" style="font-size: medium">Medium</button>
                    <button class="toolbar-button ddm"  cmd="fontSize" param="4" status="isFontSize" style="font-size: large">Large</button>
                    <button class="toolbar-button ddm"  cmd="fontSize" param="5" status="isFontSize" style="font-size: x-large">Large X</button>
                    <button class="toolbar-button ddm"  cmd="fontSize" param="6" status="isFontSize" style="font-size: xx-large">Large XX</button>
                </div>
            </div>

            <div class="dropdown">
                <button class="button" title="Change font color"><span class="icon icon202"></span><span class="toggle">&nbsp;</span></button>
                <div class="dropdown-slider" style="width:213px; padding: 10px">
                    <div class="toolbar-colorpicker" name="foreColor"></div>
                </div>
            </div>

            <div class="dropdown">
                <button class="button" title="Change font size"><span class="icon icon203"></span><span class="toggle">&nbsp;</span></button>
                <div class="dropdown-slider" style="width:213px; padding: 10px">
                    <div class="toolbar-colorpicker" name="hiliteColor"></div>
                </div>
            </div>
        </div>

        <style type="text/css">
        #demo {
            width: 800px;
            height: 400px;
            display:block;
        }
        html {
            font-size: 0.6em;
        }
        </style>

        <script type="text/javascript">
        	$(function(){
                var toolbar = $('#toolbar').wysiwygToolbar({ui: false});
                var toolbar2 = $('#toolbar2').wysiwygToolbar({ui: false});


                $('#demo').wysiwyg({
                    ui: true,
                    css: "wym.css"
                }).wysiwyg('toolbar', toolbar2)
                  .wysiwyg('toolbar', toolbar)
                  .wysiwyg('commands', {
                    link: function () {
                        var selected = this.selected();

                        if (selected) {
                            var url = prompt('Enter url', 'http://');

                            if (url) {
                                this._exec('createLink', url);
                            } else {
                                this._exec('unlink');
                            }
                        }
                    },
                    image: function() {
                	    var url = prompt('Insert image url', '');
                	    if (url) {
                            $('#demo').wysiwyg('exec', 'inserthtml', '<img src="' + url + '"/>');
                	    }
                    }
                });

        	    $('body').append(
        			$('<button>', {
        				html: 'hide',
        				click: function() {$('#demo').wysiwyg('hide')}
        			}),
        			$('<button>', {
        				html: 'show',
        				click: function() {$('#demo').wysiwyg('show')}
        			}),
        			$('<button>', {
        				html: 'enable',
        				click: function() {$('#demo').wysiwyg('enable')}
        			}),
        			$('<button>', {
        				html: 'disable',
        				click: function() {$('#demo').wysiwyg('disable')}
        			}),
        			$('<button>', {
        				html: 'alert content',
        				click: function() { alert( $('#demo').wysiwyg('html') )}
        			}),
        			$('<button>', {
        				html: 'prompt content',
        				click: function() {
        					if (html = prompt('Enter html', '')) {
        					    $('#demo').wysiwyg('html', html);
        					}
        				}
        			}),
        			$('<button>', {
        				html: 'destroy',
        				click: function() { $('#demo').wysiwyg('destroy') }
        			}),
        			$('<button>', {
        				html: 'clean',
        				click: function() { $('#demo').wysiwyg('clean') }
        			}),
        			$('<button>', {
        				html: 'Old browser usage',
        				click: function() {
        					$('#demo').wysiwyg('hide')
        					$('#demo').yourBrowserSucks({strict: false})
        					$('#demo').wysiwyg('show')
        				}
        			})
        		)

        	});
        </script>
    </body>
</html>